### ISSUE TITLE
missing dependency: PyYaml

### ISSUE THREAD

**Issue by MarcelPa** [openid/JWTConnect-Python-OidcService#2]
I tried to use oidcrp within my application, which resulted in an "ModuleNotFound" error. Upon inspection I noticed the use of the yaml module in `util.py`, which is not noted as a required dependency in `setup.py`.
Installing pyyaml using pip resolves the error, adding pyyaml to the requirements in `setup.py`should solve this issue I guess.

**Comment by rohe** [comment]
OK, I'll add pyyaml as a requirement.
