### ISSUE TITLE
[Pypi setup] ImportError: cannot import name 'init_services' from 'oidcservice.service'

### ISSUE THREAD

**Issue by peppelinux** [openid/JWTConnect-Python-OidcService#4]
We need to create a pypi realease otherwise the exception in the object will be always raised installing oidservice from oidc-op.setup and JWT-Connect-PythonRP.setup.

A this moment this function is only made available in this git master branch.

**Comment by rohe** [comment]
Will do.

**Comment by rohe** [comment]
Uploaded oidcop 0.5.2 and oidcrp 0.6.2 to pypi.
